### ISSUE TITLE
Is grid2Dto3D missing? 

### ISSUE THREAD

**Issue by matteodefelice** [SantanderMetGroup/transformeR#1]
I can see the functions `grid3Dto2Dmatrix` and similar, but I cannot see the "reverse" operations, am I missing something?

**Comment by jbedia** [comment]
Hi Matteo, you have:
`array3Dto2Dmat` and `mat2Dto3Darray`, which is the inverse operation (I know these are awful names). Type `help(array3Dto2Dmat)` for details.
The function you mention is under development, and should not be exported. Sorry for the confusion.
