### ISSUE TITLE
error in climatology

### ISSUE THREAD

**Issue by DanielaOsses** [SantanderMetGroup/transformeR#22]
Hello!

I'm trying to calculate the mean with climatology to the downscale.cv  results applied to a reanalysis multigrid data and also to my observed data but that shows an error.  "Error in aperm.default (Grid $ Data, perm)" perm "is of wrong length 3 (! = 4).

I did the downscale.cv with the iberian data and althought the structure is almost the same to my data, this does not get the error and the climatology is calculated. 

the estructure of my data is this. Please can anyone help me finding the error?

thanks

List of 5
 $ Variable:List of 1
  ..$ varName: chr "precip"
  ..- attr(*, "subset")= chr "time"
  ..- attr(*, "time_subset")= chr "getTemporalIntersection"
 $ Data    : num [1:13149, 1:427] 0 0 0 0 0 0 0 0 0 0 ...
  ..- attr(*, "dimensions")= chr [1:2] "time" "station"
 $ xyCoords: num [1:427, 1:2] -70 -70.4 -68.3 -68.3 -69.8 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:427] "chile003" "chile013" "chile017" "chile018" ...
  .. ..$ : chr [1:2] "longitude" "latitude"
 $ Dates   :List of 2
  ..$ start: chr [1:13149] "1980-01-01 12:00:00 GMT" "1980-01-02 12:00:00 GMT" "1980-01-03 12:00:00 GMT" "1980-01-04 12:00:00 GMT" ...
  ..$ end  : chr [1:13149] "1980-01-01 12:00:00 GMT" "1980-01-02 12:00:00 GMT" "1980-01-03 12:00:00 GMT" "1980-01-04 12:00:00 GMT" ...
  ..- attr(*, "season")= int [1:12] 1 2 3 4 5 6 7 8 9 10 ...
 $ Metadata:List of 2
  ..$ station_id: chr [1:427] "chile003" "chile013" "chile017" "chile018" ...
  ..$ name      : chr [1:427] "Aguas Verdes" "Antofagasta" "Ascotan" "Ayquina" ...

**Comment by miturbide** [comment]
Hi @DanielaOsses ,

The "dimensions" attribute of `$Data` for the spatial dimension should be "loc" instead of "station". 
You're probably using an old version of loadeR. I would suggest updating the packages to the latest version. 

If you change the attribute name you should have no problems computing the climatology:

> attr(grid$Data, "dimensions") <- c("time", "loc")
> climatology(grid)

**Comment by DanielaOsses** [comment]
Thanks! I didn't thought that the name could affect the calculation
