### ISSUE TITLE
How to merge grid objects?

### ISSUE THREAD

**Issue by matteodefelice** [SantanderMetGroup/transformeR#3]
In case I have multiple grid objects with the same variable and I want to join them (from a temporal point of view) in a single object, what is the suggested way to do it?

**Comment by cofinoa** [comment]
can we make it with an example or use case?

**Comment by jbedia** [comment]
Hi Matteo,
There is currently a recent option for binding grids along the `member` dimension, 
https://github.com/SantanderMetGroup/transformeR/blob/devel/R/bindGrid.member.R

The idea is implementing analogous functions for time and space dimensions, and wrap all of them in a single call to  `bindGrid `, in a similar way as  `aggregateGrid `,  `subsetGrid ` etc.  These functions are to be developed, so you are welcome to contribute!

**Comment by matteodefelice** [comment]
Ok,
I have inserted the implementation of bindGrid.time.R in my todo list, I
hope I can work on it soon!

**Comment by jbedia** [comment]
I close this now after  9b6f915 . Thanks @matteodefelice
