### ISSUE TITLE
Season of input and reference grids do not match

### ISSUE THREAD

**Issue by DanielaOsses** [SantanderMetGroup/transformeR#7]
Hola, buenas. 

Tengo una duda, al hacer el rescaleMonthlyMeans, al principio me salía el error de 
"Error in as.POSIXlt.default(sim$Dates$start) : 
  do not know how to convert 'sim$Dates$start' to class “POSIXlt”"

Luego usé para solucionar este problema
as.POSIXlt(predgcm_hist$Dates[[1]]$start)$mon + 1

pero luego de esto me apareció un error que antes no aparecía, 
Error in rescaleMonthlyMeans(pred = sub.time, sim = predgcm_hist, ref = predgcm_hist) : 
  Season of input and reference grids do not match

Fui probando en qué momento se perdían las temporadas con getSeason(predgcm_hist) y es justo después de asignarle  el "as.POSIXlt(.....)" al sim

El código es:

predrean<-"C:/Users/agroenergia/Desktop/tesis/predrean/"
predgcm<-"C:/Users/agroenergia/Desktop/tesis/predgcm/"
pca.pred<-"C:/Users/agroenergia/Desktop/tesis/estadisticas/"

esc.hist<-"historical"
escenario<-c("rcp26","rcp45","rcp85")
periodoFuturo<-c("2016-2035","2046-2065","2081-2100")
periodoHistorical<-"1986-2005"
periodoTrain<-"1980-2015"
variable<-c("precip", "tmin", "tmax")

for(v in 1:length(variable)){
  if (variable[v]=="precip"){predictor="pred8"}
  if(variable[v]=="tmin"|variable[v]=="tmax"){predictor="pred7"}
    
  #primero el HISTORICO
    load(file=paste(predgcm,esc.hist,"_",periodoHistorical,"_",predictor,".Rdata",sep="")) #datos historicos PREDGCM_hist
    load(file=paste(predrean,predictor,"_",periodoTrain,".Rdata",sep="")) #cargo datos observados PRED
    
    #subsetGrid de reanalisis
    sub.time <- subsetGrid(pred, years = 1986:2005)
    if(variable[v]=="tmin"|variable[v]=="tmax"){sub.time$Variable$varName<-c("tas","ta85000","ta70000","hus70000","hus85000")}
    if(variable[v]=="precip"){sub.time$Variable$varName<-c("zg85000","zg50000","tas")}
    
    fech_1<-as.POSIXlt(predgcm_hist$Dates[[1]]$start)$mon + 1
    fech_2<-as.POSIXlt(predgcm_hist$Dates[[2]]$start)$mon + 1
    fech_3<-as.POSIXlt(predgcm_hist$Dates[[3]]$start)$mon + 1
    feche_1<-as.POSIXlt(predgcm_hist$Dates[[1]]$end)$mon + 1
    feche_2<-as.POSIXlt(predgcm_hist$Dates[[2]]$end)$mon + 1
    feche_3<-as.POSIXlt(predgcm_hist$Dates[[3]]$end)$mon + 1

    predgcm_hist$Dates[[1]]$start<-fech_1
    predgcm_hist$Dates[[2]]$start<-fech_2
    predgcm_hist$Dates[[3]]$start<-fech_3
    predgcm_hist$Dates[[1]]$end<-feche_1
    predgcm_hist$Dates[[2]]$end<-feche_2
    predgcm_hist$Dates[[3]]$end<-feche_3

#JUSTO DESPUÉS DE ESTE PASO, cuando hago getSeason(predgcm_hist) me sale [1] NA y no los 12 meses como antes.    

    #reescalar historico
    sim.multifield.reescaled<-rescaleMonthlyMeans(pred=sub.time, sim=predgcm_hist, ref=predgcm_hist)#ref siempre es historical, pred siempre es reanalisis y sim es historical, rcp (x3)
    
    }#variable

Espero me puedan ayudar, muchas gracias.

**Comment by jbedia** [comment]
Hola Daniela, gracias por el mensaje
`rescaleMonthlyMeans` ya no debería estar ahí, disculpa las molestias, es culpa mía. La nueva función para realizar esa tarea es `rescaleGrid`. Acabo de eliminar la antigua versión para la próxima version del paquete. En caso de surgir algún otro problema  házmelo saber. SI funciona bien, por favor cierra el issue. Gracias de nuevo.

**Comment by anacv** [comment]
Gracias por la rápida respuesta Juaco. En la nueva función rescaleGrid se introducen directamente los climatologies con los que quieres rescalar, entonces para tener un resultado equivalente a lo que daba rescaleMonthlyMeans asumo que habrá que hacer primero un subsetGrid seleccionando cada mes, luego climatology y para cada mes el rescaleGrid, no? Gracias!
Ana

**Comment by jbedia** [comment]
Hola Ana. Si deseas hacer el rescalado a escala mensual sí, tendría que ser así. Si lo haces a escala estacional, y lo que tienes es un grid para una determinada season y un ref.grid estacional, entonces no haría fata desagregar mensualmente. ¿Os vendría bien que la función maneje internamente esta casuística?

**Comment by DanielaOsses** [comment]
Gracias a ambos por su ayuda. 
En cuanto a que la función maneje esto internamente, no gracias. 
Saludos
