### ISSUE TITLE
On the performances of `prinComp`

### ISSUE THREAD

**Issue by matteodefelice** [SantanderMetGroup/transformeR#9]
As you can see, I am quite interested on the performances, because loadeR + transformeR are becoming my first choice for climate data analysis but their performances are still rather poor compared to other solutions. 
I was comparing the EOF of a field obtained with `prinComp` with other similar solutions drastically faster...
I was analysing `prinComp.R` in the `lapply` at line 102. You heavier computation is the svd decomposition of the covariance matrix:
```
Cx <- cov(Xsc.list[[i]][[x]])
sv <- svd(Cx)
```
The point is that if you do instead directly `prcomp` on the original data (here `Xsc.list[[i]][[x]]`) you get the same identical results and it's definitely faster (100 times?)

Here a replicable example:
```
set.seed(1)
test = matrix(rnorm(60*1000), nrow = 60, ncol = 1000)
p1 = prcomp(test) 
cov_test = cov(test)
p2 = svd(cov_test)
print(cor(p1$rotation[,1], p2$u[,1]))
print(cor(p1$rotation[,2], p2$u[,2]))

F <- as.matrix(p2$u[, 1:3])
PCs <- test %*% p2$u

print(cor(PCs[,1], p1$x[,1]))
print(cor(PCs[,2], p1$x[,2]))
```
`p2` is the EOF computed as implemented in `prinComp`. 
What is your opinion about this? 
**UPDATE** I have created a pull request. Older version took 1.4 minutes to compute the first 3 EOFs on a 60x46x68 grid file. The prcomp version takes 0.11 seconds.

**Comment by jbedia** [comment]
Hi Matteo, thanks for looking at this issue, certainly interesting and for sure a bottleneck in many applications. Of course, singular value decomposition is a computationally expensive task. However, I am not sure if I fully understood, but my tests do not indicate any significant performance improvement with the proposed change:

```R
source("https://github.com/matteodefelice/transformeR/blob/309fe615347f9686cdad4a241008698c19ec6d7d/R/prinComp.R?raw=True")
prinComp.new <- prinComp

library(transformeR)
library(microbenchmark)
library(magrittr)

data("iberia_ncep_hus850")
data("iberia_ncep_psl")
data("iberia_ncep_ta850")

mg <- makeMultiGrid(iberia_ncep_hus850, iberia_ncep_psl, iberia_ncep_ta850)

test <- microbenchmark(prinComp = {pca <- prinComp(mg, v.exp = .95)},
                       prinComp.new = {pca.new <- prinComp.new(mg, v.exp = .95)},
                       times = 10)
boxplot(test)
```

![image](https://user-images.githubusercontent.com/5796721/27386980-b6496172-5697-11e7-8b66-583506e2bc8f.png)

**Comment by gutierjm** [comment]
mola el microbenchmarking :)

Enviado desde mi iPhone

El 21 jun 2017, a las 15:41, Joaquin Bedia <notifications@github.com<mailto:notifications@github.com>> escribi?:


Hi Matteo, thanks for looking at this issue, certainly interesting and for sure a bottleneck in many applications. Of course, singular value decomposition is a computationally expensive task. However, I am not sure if I fully understood, but my tests do not indicate any significant performance improvement with the proposed change:

source("https://github.com/matteodefelice/transformeR/blob/309fe615347f9686cdad4a241008698c19ec6d7d/R/prinComp.R?raw=True")
prinComp.new <- prinComp

library(transformeR)
library(microbenchmark)
library(magrittr)

data("iberia_ncep_hus850")
data("iberia_ncep_psl")
data("iberia_ncep_ta850")

mg <- makeMultiGrid(iberia_ncep_hus850, iberia_ncep_psl, iberia_ncep_ta850)

test <- microbenchmark(prinComp = {pca <- prinComp(mg, v.exp = .95)},
                       prinComp.new = {pca.new <- prinComp.new(mg, v.exp = .95)},
                       times = 10)
boxplot(test)

[image]<https://user-images.githubusercontent.com/5796721/27386980-b6496172-5697-11e7-8b66-583506e2bc8f.png>

-

**Comment by matteodefelice** [comment]
@jbedia Maybe because you are using datasets with a different shape, when computing the PCA the data matrix is very tall (n. of rows >> n. of columns). Try with a "wider" dataset,  like this one: https://www.dropbox.com/s/9rallml158blfcy/erai_mslp_JJA.nc?dl=0

**Comment by jbedia** [comment]
hi @matteodefelice. Still the same result (see my code below). In any case, `svd` is quite standard function in many languajes, not just R, written in LAPACK. Its main advantage is that it provides a better numerical stability as compared to `eigen`. Despite I ignore the details, I don't think `prcomp` is doing something very different than just calling `svd ` and returning the corresponding S3 object for convenience (being perhaps the S3 conversion the responsible of a negligible overhead). It is very difficult to believe that it will improve the performance of `svd` by 2 orders of magnitude, otherwise being very clearly indicated in the help files.

```R
library(loadeR)
msl <- loadGridData("erai_mslp_JJA.nc", var = "msl")
source("https://github.com/matteodefelice/transformeR/blob/309fe615347f9686cdad4a241008698c19ec6d7d/R/prinComp.R?raw=True")
prinComp.new <- prinComp

library(transformeR)
library(microbenchmark)
library(magrittr)

test <- microbenchmark(prinComp = {pca <- prinComp(msl, v.exp = .95)},
                       prinComp.new = {pca.new <- prinComp.new(msl, v.exp = .95)},
                       times = 10)
boxplot(test, main = "Using the MSLP example data")
```
![image](https://user-images.githubusercontent.com/5796721/27390152-d3967374-56a0-11e7-9532-bf71ea4d5996.png)

**Comment by matteodefelice** [comment]
I get something totally different, in milliseconds: 
- prinComp mean 86315 
- prinComp.new mean 103
However, I think that `prcomp` does not compute the covariance matrix, that's why I supposed it was faster...

**Comment by jbedia** [comment]
What do you think? How is it possible we get so wildly differing results?

**Comment by matteodefelice** [comment]
Are you sure you that `prinComp` and `prinComp.new` are different? Check!

**Comment by matteodefelice** [comment]
(and btw, can you run the comparison with random data?)

**Comment by matteodefelice** [comment]
I confirm my first impression. If the matrix is wide (n. columns >> n. of rows) `prcomp` is faster, if is tall is `svd` the winner. 
Here a few numbers. 
matrix 1000 rows x 60 columns: prcomp 15 ms, svd 2648 ms (mean)
matrix 60 rows x 1000 columns: prcomp 15 ms, svd 2 ms (mean)

**Comment by matteodefelice** [comment]
Last comment from Math.stackexchange:

> In fact, using the SVD to perform PCA makes much better sense numerically than forming the covariance matrix to begin with

It's the first answer here https://math.stackexchange.com/questions/3869/what-is-the-intuitive-relationship-between-svd-and-pca

**Comment by jbedia** [comment]
Hi @matteodefelice , yes, I see the point now with the simulated datasets. Here I will analyse the two cases, considering two matrices of 60000 points but of different sizes:

```R
source("https://github.com/matteodefelice/transformeR/blob/309fe615347f9686cdad4a241008698c19ec6d7d/R/prinComp.R?raw=True")
prinComp.new <- prinComp
rm(prinComp) # just to be sure...
library(transformeR)
library(microbenchmark)
library(magrittr)

data("iberia_ncep_psl")
```

# Case I

In this case we analyse a relatively long time series (n = 1000, this could be daily or sub-daily data, for instance) for a relatively small spatial domain (just 6 `x` 10 points). In this case, we don't find significant differences between both approaches:

```R
arr <- array(runif(6e04), dim = c(1000,6,10))
attr(arr, "dimensions") <- c("time", "lat", "lon")
iberia_ncep_psl$Data <- arr
test <- microbenchmark(prinComp = {pca <- transformeR::prinComp(iberia_ncep_psl, v.exp = .95)},
                       prinComp.new = {pca.new <- prinComp.new(iberia_ncep_psl, v.exp = .95)},
                       times = 100)
boxplot(test, main = "1000 rows, 60 columns")
```

![image](https://user-images.githubusercontent.com/5796721/27421848-65b742de-572c-11e7-86ee-463cba841cb2.png)

# Case II

And this is the case you refer to, in which there are a few rows (e.g., a short time period or annually aggregated data) and many columns (100 `x` 10 e.g., a large domain, possibly global, and/or a very high spatial resolution dataset):

```R
arr <- array(runif(6e04), dim = c(60,100,10))
attr(arr, "dimensions") <- c("time", "lat", "lon")
iberia_ncep_psl$Data <- arr
test <- microbenchmark(prinComp = {pca <- transformeR::prinComp(iberia_ncep_psl, v.exp = .95)},
                       prinComp.new = {pca.new <- prinComp.new(iberia_ncep_psl, v.exp = .95)},
                       times = 100)
boxplot(test, main = "60 rows, 1000 columns")
```

![image](https://user-images.githubusercontent.com/5796721/27421837-57384bae-572c-11e7-9838-cf3f36848009.png)


So many thanks again for raising this issue.

**Comment by matteodefelice** [comment]
I would suggest here to insert a `method` parameter in the `prinComp` function that allow the user to choose between `auto`, `svd` and `prcomp`. The `auto` would select the best method according to the 'shape' of the data matrix (wide or tall). What do you think?

**Comment by jbedia** [comment]
In any case, I would avoid so many options. Your `prcomp` approach seems more straightforward and performs much better under certain circumstances (e.g. Case II), while performs equally well under others (Case I), so what would be the added value of maintaining cov + svd, and complicating ourselves and the users with the additional `auto`? What do you think?

**Comment by matteodefelice** [comment]
I agree, although in case of very tall matrices the `svd` approach seems faster, but perhaps this is too sporadic. I am really happy about this improvement in performances, this analysis started because I was comparing the performance of a python-based climate library (iris) that is take advantage of the MKL libraries (freely available for the `numpy` library provided by conda!).

**Comment by jesusff** [comment]
Hi,

it is not an sporadic behaviour. If the data matrix is not full rank
(e.g. less rows than columns) there are multiple zero-value eigenvalues,
and their eigenvectors are degenerated and not fully defined (and
library dependent). This can lead to numerical problems. SVD is the
preferred approach, not only because of speed but for numerical stability.

The covariance matrix approach has some advantage in case of missing
data, because it can still be computed.

HTH,

Cheers
Chus
--
Jesus FERNANDEZ
Meteorology Group (http://www.meteo.unican.es)
Depto. Matematica Aplicada y CC de la Computacion
Universidad de Cantabria
ETSI de Caminos, Canales y Puertos (Despacho 1034)
Avenida de los Castros s/n. 39005 Santander. SPAIN
Tel: (+34) 942 20 1723

**Comment by jbedia** [comment]
Excellent. Yes, I think we should definitely adopt the prcomp approach by the moment. Can I go ahead with the merge request?

**Comment by matteodefelice** [comment]
Well, I am not in charge on this :) I mean, I would prefer the have the possibility to choose the method, especially considering the comment by @jesusff , what will happen in case of NAs? However, my main concern now is the performance of PCA/EOF, because the datasets I'm currently using are particularly big!

**Comment by jbedia** [comment]
Merged into devel. To be included in the next package release. Grazie!
